apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fam-admin-cluster-role
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["services", "pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fam-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fam-admin-cluster-role
subjects:
  - kind: ServiceAccount
    name: fam-service-account
    namespace: fam-ns
