apiVersion: v1
kind: Namespace
metadata:
  name: fam-ns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fam-service-account
  namespace: fam-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fam-deployment
  namespace: fam-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fam
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fam
    spec:
      serviceAccountName: fam-service-account
      restartPolicy: Always
      containers:
        - name: fam-instance
          image: docker.io/mediandxz/fam:latest
          resources:
            limits:
              memory: "256Mi"
              cpu: "0.5"
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          # env:
          #   - name: KUBERNETES_NAMESPACE
          #     valueFrom:
          #       fieldRef:
          #         apiVersion: v1
          #         fieldPath: metadata.namespace
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            runAsUser: 1001
            runAsGroup: 1001
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: fam-service
  namespace: fam-ns
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: fam
  ports:
    - port: 3000
      targetPort: 3000
